version: 2

jobs:
  one:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "A first build"
  two:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "a second build!"

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two