version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "app/package.json" }} 
      - run: cd app && npm install
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "app/package.json" }}
          paths:
            - app/node_modules